import React,{useState} from 'react'; import {createRoot} from 'react-dom/client'; import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query'; import {Search,ChevronRight,ArrowLeft,Play,SlidersHorizontal} from 'lucide-react'; import './styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
type Show={slug:string;title:string;synopsis:string;section:string;categories:string[];artwork:Record<string,string>;episodes:any[];seasons:any[];trailers:any[]};
async function get(path:string){const r=await fetch(API+path);if(!r.ok)throw new Error('The catalogue could not be loaded.');return r.json()}
function App(){const [selected,setSelected]=useState<Show|null>(null); const [query,setQuery]=useState(''); const [category,setCategory]=useState(''); const [language,setLanguage]=useState(''); const {data,error,isLoading}=useQuery({queryKey:['catalog',query,category,language],queryFn:()=>get(query||category||language?`/catalog/search?q=${encodeURIComponent(query)}&category=${category}&language=${language}`:'/catalog')}); if(selected)return <Detail show={selected} onBack={()=>setSelected(null)}/>; if(isLoading)return <div className="page loading">Loading your library…</div>; if(error)return <div className="page center">Couldn’t load the catalogue. Please try again.</div>; const sections=data?.sections||{}; const searchItems=data?.items; const rows=searchItems?{search:searchItems}:sections; return <div className="page"><Nav query={query} setQuery={setQuery}/>{query||category||language?<SearchResults items={searchItems||[]} onOpen={setSelected} category={category} setCategory={setCategory} language={language} setLanguage={setLanguage}/>:<><Hero show={sections.featured?.[0]} onOpen={setSelected}/>{['featured','series','minisodes','songs'].map(sec=>rows[sec]?.length?<Row key={sec} title={secLabel(sec)} shows={rows[sec]} onOpen={setSelected}/>:null)}</>}</div>}
function Nav({query,setQuery}:{query:string;setQuery:(x:string)=>void}){return <header className="nav"><button className="logo" onClick={()=>{setQuery('');location.hash=''}}>peblo<span>tv</span></button><div className="nav-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search shows, episodes, categories"/></div></header>}
function Hero({show,onOpen}:{show?:Show;onOpen:(s:Show)=>void}){if(!show)return <div className="hero empty-hero">Your library is ready for its first feature.</div>; return <div className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(31,26,48,.96),rgba(31,26,48,.62) 48%,rgba(31,26,48,.12)),url(${API+show.artwork.banner})`}}><div className="hero-copy"><div className="eyebrow">Featured</div><h1>{show.title}</h1><p>{show.synopsis}</p><div className="tags">{show.categories.slice(0,3).map(c=><span key={c}>{c}</span>)}</div><button className="watch" onClick={()=>onOpen(show)}><Play size={16} fill="currentColor"/> Explore show</button></div></div>}
function Row({title,shows,onOpen}:{title:string;shows:Show[];onOpen:(s:Show)=>void}){return <section className="row"><div className="row-title"><h2>{title}</h2><span>{shows.length}</span></div><div className="cards">{shows.map(s=><button className="card" key={s.slug} onClick={()=>onOpen(s)}><img src={API+s.artwork.poster} loading="lazy"/><div className="card-copy"><b>{s.title}</b><small>{s.categories.slice(0,2).join(' · ')}</small></div></button>)}</div></section>}
function SearchResults({items,onOpen,category,setCategory,language,setLanguage}:{items:Show[];onOpen:(s:Show)=>void;category:string;setCategory:(x:string)=>void;language:string;setLanguage:(x:string)=>void}){return <main><div className="filterbar"><div><SlidersHorizontal size={16}/> Filters</div><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{['adventure','folk','friendship','india','language','learning','maths','music','nature','reading','science','singalong','stories','travel','values'].map(x=><option key={x}>{x}</option>)}</select><select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">All languages</option><option value="en">English</option><option value="hi">Hindi</option></select></div>{items.length?<div className="result-grid">{items.map(s=><button className="result" key={s.slug} onClick={()=>onOpen(s)}><img src={API+s.artwork.poster}/><div><h3>{s.title}</h3><p>{s.synopsis}</p><small>{s.categories.join(' · ')}</small></div></button>)}</div>:<div className="not-found"><h2>Nothing quite matched.</h2><p>Try a shorter search or remove one of the filters.</p></div>}</main>}
function Detail({show,onBack}:{show:Show;onBack:()=>void}){return <div className="detail"><button className="back" onClick={onBack}><ArrowLeft size={17}/> Back to browse</button><div className="detail-hero" style={{backgroundImage:`linear-gradient(0deg,#211b30 0%,rgba(33,27,48,.45) 70%),url(${API+show.artwork.banner})`}}><div><div className="eyebrow">{show.section}</div><h1>{show.title}</h1><p>{show.synopsis}</p><div className="tags">{show.categories.map(c=><span key={c}>{c}</span>)}</div></div></div><div className="detail-body"><div className="detail-heading"><div><h2>Episodes</h2><p>Choose a story. Language options stay together.</p></div>{show.trailers?.length>0&&<span className="trailer-note">Trailer available</span>}</div>{show.seasons?.map((season:any)=><div className="season" key={season.number}><h3>Season {season.number}</h3><div className="episodes">{season.episodes.map((ep:any)=><div className="episode" key={ep.content_group}><img src={API+ep.artwork.thumbnail} loading="lazy"/><div><b>{ep.episode_number?`Episode ${ep.episode_number}`:''} · {ep.episode_title}</b><p>{Math.round(ep.duration_seconds/60)} min · {ep.languages.map((l:string)=>l.toUpperCase()).join(' / ')}</p></div></div>)}</div></div>)}</div></div>}
function secLabel(x:string){return x==='minisodes'?'Minisodes':x[0].toUpperCase()+x.slice(1)}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);
